"""init all tables

Revision ID: 7df5d0613ffb
Revises: 
Create Date: 2026-05-12 20:38:35.858614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df5d0613ffb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('global_variables', sa.Text(), nullable=False),
    sa.Column('global_params', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['api_categories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_categories_parent_id'), 'api_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_api_categories_project_id'), 'api_categories', ['project_id'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('services', sa.Text(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=False),
    sa.Column('headers', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_project_id'), 'environments', ['project_id'], unique=False)
    op.create_table('mock_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.String(length=10), nullable=False),
    sa.Column('match_path', sa.String(length=500), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_headers', sa.Text(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('response_delay', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_rules_project_id'), 'mock_rules', ['project_id'], unique=False)
    op.create_table('test_scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('env_id', sa.Integer(), nullable=True),
    sa.Column('loop_count', sa.Integer(), nullable=False),
    sa.Column('thread_count', sa.Integer(), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('on_failure', sa.String(length=20), nullable=False),
    sa.Column('on_error', sa.String(length=30), nullable=False),
    sa.Column('save_detail', sa.String(length=20), nullable=False),
    sa.Column('save_vars', sa.Integer(), nullable=False),
    sa.Column('global_cookie', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('save_cookie_to_global', sa.Integer(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('schedule_env_id', sa.Integer(), nullable=True),
    sa.Column('schedule_enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_scenes_project_id'), 'test_scenes', ['project_id'], unique=False)
    op.create_table('api_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('headers', sa.Text(), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['api_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_definitions_category_id'), 'api_definitions', ['category_id'], unique=False)
    op.create_index(op.f('ix_api_definitions_project_id'), 'api_definitions', ['project_id'], unique=False)
    op.create_table('scene_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('edge_id', sa.String(length=50), nullable=False),
    sa.Column('source_node_id', sa.String(length=50), nullable=False),
    sa.Column('target_node_id', sa.String(length=50), nullable=False),
    sa.Column('source_handle', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['test_scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_edges_scene_id'), 'scene_edges', ['scene_id'], unique=False)
    op.create_table('test_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('skip_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['test_scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_reports_project_id'), 'test_reports', ['project_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('assertions', sa.Text(), nullable=False),
    sa.Column('extract_vars', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_project_id'), 'test_cases', ['project_id'], unique=False)
    op.create_table('scene_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('query_params', sa.Text(), nullable=True),
    sa.Column('assertions', sa.Text(), nullable=True),
    sa.Column('extract_vars', sa.Text(), nullable=True),
    sa.Column('condition_expression', sa.Text(), nullable=True),
    sa.Column('loop_count', sa.Integer(), nullable=True),
    sa.Column('loop_variable', sa.String(length=100), nullable=True),
    sa.Column('wait_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['test_scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_steps_scene_id'), 'scene_steps', ['scene_id'], unique=False)
    op.create_table('report_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('scene_step_id', sa.Integer(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=False),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_headers', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('assertions', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['test_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['test_scenes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_step_id'], ['scene_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_steps_report_id'), 'report_steps', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_steps_report_id'), table_name='report_steps')
    op.drop_table('report_steps')
    op.drop_index(op.f('ix_scene_steps_scene_id'), table_name='scene_steps')
    op.drop_table('scene_steps')
    op.drop_index(op.f('ix_test_cases_project_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_test_reports_project_id'), table_name='test_reports')
    op.drop_table('test_reports')
    op.drop_index(op.f('ix_scene_edges_scene_id'), table_name='scene_edges')
    op.drop_table('scene_edges')
    op.drop_index(op.f('ix_api_definitions_project_id'), table_name='api_definitions')
    op.drop_index(op.f('ix_api_definitions_category_id'), table_name='api_definitions')
    op.drop_table('api_definitions')
    op.drop_index(op.f('ix_test_scenes_project_id'), table_name='test_scenes')
    op.drop_table('test_scenes')
    op.drop_index(op.f('ix_mock_rules_project_id'), table_name='mock_rules')
    op.drop_table('mock_rules')
    op.drop_index(op.f('ix_environments_project_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_api_categories_project_id'), table_name='api_categories')
    op.drop_index(op.f('ix_api_categories_parent_id'), table_name='api_categories')
    op.drop_table('api_categories')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
