"""add pre_post_script_cookies_auth_settings

Revision ID: 7ffe1387f512
Revises: 6a1b2c3d4e5f
Create Date: 2026-05-17 01:04:05.913766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ffe1387f512'
down_revision: Union[str, None] = '6a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite 不支持 ADD COLUMN NOT NULL，用 nullable=True 兼容已有数据
    op.add_column('api_definitions', sa.Column('pre_script', sa.Text(), nullable=True))
    op.add_column('api_definitions', sa.Column('post_script', sa.Text(), nullable=True))
    op.add_column('api_definitions', sa.Column('cookies', sa.Text(), nullable=True))
    op.add_column('api_definitions', sa.Column('auth', sa.Text(), nullable=True))
    op.add_column('api_definitions', sa.Column('settings', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_definitions', 'settings')
    op.drop_column('api_definitions', 'auth')
    op.drop_column('api_definitions', 'cookies')
    op.drop_column('api_definitions', 'post_script')
    op.drop_column('api_definitions', 'pre_script')
    # ### end Alembic commands ###
