"""add deleted_at for soft delete

Revision ID: badded1ae03b
Revises: 7ffe1387f512
Create Date: 2026-05-17 09:17:34.659646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'badded1ae03b'
down_revision: Union[str, None] = '7ffe1387f512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_definitions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('test_cases', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('test_scenes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_scenes', 'deleted_at')
    op.drop_column('test_cases', 'deleted_at')
    op.drop_column('api_definitions', 'deleted_at')
    # ### end Alembic commands ###
